# Généré automatiquement par 01_create_topology.yml
# Projet: Lab_ARP_Switching
project_id: "cb7a2072-3789-4e12-a7bd-ea946f09bbe1"
sw1_console_port: 5000
sw2_console_port: 5001
sw1_node_id: "5b39c915-e6a1-40cf-b7cd-348c1edcb0db"
sw2_node_id: "20779690-aa75-4097-88d4-3cdee15bcef8"
