services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"	
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_site:/usr/share/nginx/html/static_site:ro
      - ./app/static:/usr/share/nginx/html/app/static:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - flask_app
    networks:
      - web_network
    restart: unless-stopped

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app:ro
      - ./run.py:/app/run.py:ro
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=cryptotavern2025
      - APPLICATION_ROOT=/app
    networks:
      - web_network
    restart: unless-stopped

networks:
  web_network:
    driver: bridge
